config/routes.rb
Rails.application.routes.draw do
  get 'patient/edit'

  devise_for :users
	
	scope "/admin" do
  	resources :users do 
  		get :handle_promotion
  	end
	end
	
	get 'home/choose_site', to: 'home#choose_site', :as => :choose_site

	root to: "home#index"
		 
	resources :users

	resources :patients
	 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  scope :admins, -> { where(:is_admin => true ) } # User.admins
  scope :patients, -> { where(:is_admin => false) } # User.patients
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :email, :presence => true
  def is_admin?
    self.is_admin == true
  end

end

app/controllers/application_controller.rb
class ApplicationController <  ActionController::Base
	protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

	def after_sign_in_path_for(resource)
		choose_site_path
  end 	

	protected

  def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :date_of_birth, :email, :password, :is_admin, :password_confirmation, :phone_number, :avatar, :school_id])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!, only: [:choose_site]
  def index
		redirect_to choose_site_path if user_signed_in?
  end

  def choose_site
  	if current_user.is_admin?
  		redirect_to users_path
  	else
  		redirect_to edit_patient_path(current_user)
  	end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy] 
  def index
  
  end

  def show

  end  
  
  def edit
  end

  def update
  	 if @patient.update(patient_params)
			redirect_to @patient 	
  	else
  		render 'edit'
  	end
  end

  private

  def set_patient
  	@patient = User.find(params[:id])
  end
  def patient_params
  	params.require(:user).permit(:name, :phone_number, :email, :date_of_birth)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_admin

	def index
		@users = User.all
	end

	def new

	end

	def edit
	end

	def show
		@user = User.find(params[:id])
	end

	def handle_promotion
		user = User.find(params[:user_id])
		user.update(is_admin: !@user.is_admin)
		redirect_to users_path
	end

	def update
	end

	def destroy
		user = User.find(params[:id])
		user.destroy
		return redirect_to users_path, notice: "One user is deleted"
	end

	private 

	def authenticate_admin
		if current_user.is_admin? == false
			redirect_to root_path, :notice => "You are not allowed to perform this action."
		end
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin.html.erb
<%= link_to "users", users_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Web Development', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
      </ul> 
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      Web Development
    </title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= render  :partial=>'/layouts/header' %>
      <%= yield %>
    </div>
    <div class="container">
      <% if user_signed_in? %>
        <% if current_user.is_admin? %>       
          <%= render :partial =>'layouts/admin' %>
        <% else %>  
          i am good
        <% end %>        
       <% end %>
    </div>
  </body>
</html>

app/views/patients/edit.html.erb
<div class="container">
	<%= semantic_form_for @patient, :url => patient_path(@patient), :html => { :method => 'put'}  do |f| %>
		<%= f.input :name %>
		<%= f.input :email %>
		<%= f.input :date_of_birth %>
		<%= f.input :phone_number %>
		<%= f.action :submit %>
	<% end  %>
</div>

app/views/users/index.html.erb
    <p id="notice"><%= notice %></p>

<h1 align="center">Users</h1>

<table class="table table-responsive table-bordered" id="users"> 
  <thead>
    <tr>
      <th>S.N</th>
      <th>Name</th>
      <th>Email</th>
      <th>Date of birth</th>
      <th>Phone number</th>
      <th>Is admin?</th>
      <th>Actions</th>
      <th>Actions</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>

    <% @users.each_with_index do |user,i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%=user.name %></td>
        <td><%=user.email %></td>
        <td><%=user.date_of_birth %></td>
        <td><%=user.phone_number %></td>
        <td> <%= user.is_admin? ? "Yes" : "No" %> </td> 
        <td><%= link_to user.is_admin? ? "Demote" : "Promote",  user_handle_promotion_path(user) %></td>
        <td><%= link_to 'Show',user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy',user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Newuser', new_user_path %>

app/views/users/new.html.erb
asdasdf

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
	<p>
  	<b>Name:</b>
  		<%= @user.name %>
		</p>
	<p>
  	<b>Email:</b>
  		<%= @user.email %>
		</p>
	<p>
  	<b>Phone Number:</b>
  		<%= @user.phone_number %>
		</p>
  
<!-- /posts/:post_id/comments/ -->
		<%= link_to 'Edit', edit_user_path(@user) %> |
		<%= link_to 'Back', users_path %>